### ISSUE TITLE
tracking_model.dat "forbidden" link?

### ISSUE THREAD

**Issue by gciccarelli3** [MLSpeech/DeepFormants#1]
Hi,

I saw your repo, but I can't access the tracking_model.dat
You don't have permission to access /~jkeshet/deep_formants/tracking_model.dat on this server.

**Comment by jkeshet** [comment]
We are in a process of uploading it… it will take few days

On 28 Jun 2016, at 11:21, gciccarelli3 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

I saw your repo, but I can't access the tracking_model.dat
You don't have permission to access /~jkeshet/deep_formants/tracking_model.dat on this server.

**Comment by gciccarelli3** [comment]
I look forward to it, as well as any docs/info on the corpus used for training, and how you validated its accuracy.

**Comment by jkeshet** [comment]
You can read more about it here:
http://u.cs.biu.ac.il/~jkeshet/papers/DissenKe16.pdf

On 28 Jun 2016, at 11:32, gciccarelli3 <notifications@github.com<mailto:notifications@github.com>> wrote:

I look forward to it, as well as any docs/info on the corpus used for training, and how you validated its accuracy.

**Comment by jkeshet** [comment]
Should work now. The link has been updated.
