### ISSUE TITLE
[Errno 2] No such file or directory: 'model.json'

### ISSUE THREAD

**Issue by HaoningChen85** [MLSpeech/DeepFormants#4]
I encountered the above problem while running VTR_Results.py
and I cannot find any json files in the directory. 
I am new to python. Can I get some help here?

**Comment by Shuadissen** [comment]
The VTR results isn't necessary for formant estimation or tracking.
It's just an evaluation file for a previous version of the code (When it was written in keras and not torch)

**Comment by HaoningChen85** [comment]
Thanks for replying! But now I have encountered another problem.
I am running this code in Windows10 with Python2.7(Anaconda2), but the SoX file cannot be found. 

I'm sure that I have a SoX file, and it has been successfully installed in the terminal. 
Is there anything wrong with the path variables?






------------------ 原始邮件 ------------------
发件人: "Shua Dissen"<notifications@github.com>;
发送时间: 2019年5月19日(星期天) 晚上11:54
收件人: "MLSpeech/DeepFormants"<DeepFormants@noreply.github.com>;
抄送: "泉水叮咚"<214969207@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [MLSpeech/DeepFormants] [Errno 2] No such file or directory:'model.json' (#4)




The VTR results isn't necessary for formant estimation or tracking.
 It's just an evaluation file for a previous version of the code (When it was written in keras and not torch)

**Comment by HaoningChen85** [comment]
The previous problem has been solved, but I have met another one. 
I cannot install scikits on windows10. 
Is it necessary to use "sudo" if I want to install scikits?
But it seems that "sudo" is not available in windows.
